[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"

[functions]
  directory = "dist"
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
